t_res_ms: 40

q_in_db: -6
q_out_db: -8

n310: 1
n311: 1
t310_ms: 1000

t_ho_prep_ms_simulated: 40
t_ho_exec_ms_simulated: 80
t_rlfr_ms_simulated: 1000
t_mts_ms: 1000

l3_filter_coef: 1
ho_event_config:
  a3:
    ttt_ms: 0
    hys: 0
    offset: 0